ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.example.MainKt.module ]
    }
}

jwt {
    secret = "my-super-secret-key-for-hotel-app-2024"
    issuer = "hotel-app"
    audience = "hotel-app-users"
    realm = "hotel app"
}

database {
    url = "jdbc:postgresql://ep-summer-mouse-alxwmgl6.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require"
    user = "neondb_owner"
    password = "npg_ZMGP27JCobQB"
    driver = "org.postgresql.Driver"
}